name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Autodetect
    provider: lmstudio
    model: AUTODETECT
    apiBase: http://localhost:1234/v1/
  - name: Gemini 2.5 Pro
    provider: gemini
    model: gemini-2.5-pro
    apiKey: <GEMINI_API_KEY>
  - name: Gemini 2.0 Flash
    provider: gemini
    model: gemini-2.0-flash
    apiKey: <GEMINI_API_KEY>
  - name: Qwen3-Coder
    provider: openai
    model: qwen3-coder-plus
    apiBase: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
    apiKey: <GEMINI_API_KEY> 
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
